### ISSUE TITLE
HRC 20 Transactions not displayed

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/onewallet#10]
Used the BUSD faucet and claimed 100 BUSD on Testnet.
Dashboard shows 100 BUSD in balance, but does not show HRC20 Transactions
Tried with multiple browsers. (Chrome/Firefox/Brave)
![image](https://user-images.githubusercontent.com/29485946/87218209-b25e7400-c361-11ea-8958-48a8dd7ab923.png)

Case 1)
http://hrc20.easy-staking.com:8080/#/address/one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl?txType=hrc20

Case 2)
http://hrc20.easy-staking.com:8080/#/address/one1s0g5tt3se3qfwv9fn4zwtwvj4fdvefxvxn4nwh?txType=hrc20

**Comment by raptor1001** [comment]
hey @mirrormirage0 Is this the testnet or mainnet explorer?

**Comment by yelllowsin** [comment]
> hey @mirrormirage0 Is this the testnet or mainnet explorer? FYI, in this wallet, BUSD is deployed on the testnet only

@raptor1001 Yes, this is poiting to the testnet explorer: http://hrc20.easy-staking.com:8080/#/

The issue is that the txs are being shown on the "Transactions" tab. Instead they should be on the "HRC20 Transactions" tab.

![image](https://user-images.githubusercontent.com/7217595/87975148-9cf3f300-caa1-11ea-9c5a-0a5ee15854af.png)


But i don't think it is you who is working on the block explorer, right? We need to transfer this issue to the dev working on the this new block explorer.

**Comment by raptor1001** [comment]
is fixed
